# Generated by Django 5.2.1 on 2025-05-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="player",
            table="players",
        ),
    ]
